eCommerce/Models/PanierViewModel.cs
using eCommerce.Business;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace eCommerce.Models
{
    public class PanierViewModel
    {
        public PanierViewModel(Commande cmd)
        {

        }


    }
}

eCommerce/Controllers/CommandeController.cs
using eCommerce.Business;
using eCommerce.Infrastructure;
using System;
using System.Data.Entity;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCommerce.Controllers
{
    public class CommandeController : CommerceControllerBase
    {
        public ActionResult Display(int id)
        {
            return View(DbContext.Commande.Include("LignesCommande.Produit").Single(c => c.Id == id));
        }

        public ActionResult Create()
        {
            Commande nvlleCommande = Panier;
            nvlleCommande.Statut = CommandeStatut.Validee;
            nvlleCommande.ValidationDate = DateTime.Now;
            DbContext.Commande.Add(nvlleCommande);
            DbContext.SaveChanges();

            Session.Remove("Panier");

            return RedirectToAction("Display",new { id = nvlleCommande.Id });
        }
    }
}

eCommerce/Controllers/PanierController.cs
using eCommerce.Business;
using eCommerce.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace eCommerce.Controllers
{
    public class PanierController : CommerceControllerBase
    {
        public ActionResult Index()
        {
            return View(Panier);
        }

        [HttpPost]
        public ActionResult Ajouter(int? id)
        {
            if (!id.HasValue)
            {
                return View("Error");
            }

            Produit p = DbContext.Produits.Find(id);
            Panier.AjouterProduit(p, 1);
            return RedirectToAction("Index", "Produit");
        }
    }
}

eCommerce/Views/Panier/Index.cshtml
@model eCommerce.Business.Commande

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <thead>
        <tr>
            <th>Nom</th>
            <th>Quantite</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.LignesCommande)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Produit.Nom)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantite)
                </td>
            </tr>
        }
    </tbody>
</table>
<div>Prix total : @Html.DisplayFor(m => m.PrixTotal);</div>
@Html.ActionLink("Commander", "Create", "Commande")