eCommerce/Controllers/ProduitController.cs
using eCommerce.Business;
using eCommerce.Infrastructure;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;

namespace eCommerce.Controllers
{
    public class ProduitController : CommerceControllerBase
    {
        public ActionResult Index(int? id)
        {
            // Rappel, ici id = id de la catégorie
            IEnumerable<Produit> produits = DbContext.Produits.Include(p => p.Categorie).Where(p => p.Categorie.Id == id || !id.HasValue);

            return View(produits);
        }
    }
}

eCommerce/Views/Shared/_Layout.cshtml
@using eCommerce.Business
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nom d'application", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Accueil", "Index", "Home")</li>
                    <li>@Html.ActionLink("Catalogue", "Index", "Produit")</li>
                    <li>@Html.ActionLink("Panier(" + ((Commande)Session["Panier"]).NbArticles + ")", "Index", "Panier")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>